[[main]]
none = "none"

[[main]]
name = "Programme"
pageRef = "programme"
identifier = "smADjJPJrg"
weight = 10

[[main]]
name = "Calendar"
pageRef = "calendar"
identifier = "calendar"
weight = 15

[[main]]
name = "Collaborators"
pageRef = "collaborators"
identifier = "tmADjJPJrg"
weight = 20

[[footer]]
none = "none"
